name: Build Mod

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: geode-sdk/build-geode-mod@v2
        with:
          target: android64
